name: tag
on:
  push:
    tags:
      - '*'
jobs:
  image-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, tag, and push image
        env:
          IMAGE: ghcr.io/colossyan/aws-cli-helm
          HELM_VERSION: "3.7.2"
        # TODO determin version based on tags
        run: |
          IMAGE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          docker build \
            --build-arg HELM_VERSION \
            -t $IMAGE:$IMAGE_TAG .
          docker push $IMAGE:$IMAGE_TAG